sbatch tpun_tree_auto_0.scr
sbatch tpun_tree_auto_1.scr
sbatch tpun_tree_auto_2.scr
sbatch tpun_tree_auto_3.scr
sbatch tpun_tree_auto_4.scr
sbatch tpun_tree_rev_0.scr
sbatch tpun_tree_rev_1.scr
sbatch tpun_tree_rev_2.scr
sbatch tpun_tree_rev_3.scr
sbatch tpun_tree_rev_4.scr
sbatch tpun_tree_interleave_0.scr
sbatch tpun_tree_interleave_1.scr
sbatch tpun_tree_interleave_2.scr
sbatch tpun_tree_interleave_3.scr
sbatch tpun_tree_interleave_4.scr
sbatch tpun_tree_sort_0.scr
sbatch tpun_tree_sort_1.scr
sbatch tpun_tree_sort_2.scr
sbatch tpun_tree_sort_3.scr
sbatch tpun_tree_sort_4.scr
